### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by andypf** [flystack/misty#103]
I tried to get the share types from the manila service 
`misty.shared_file_systems.list_share_types`

The following error has appeared:
`ArgumentError: Not enough arguments`

**Backtrace**
```
lib/misty/http/method_builder.rb:91:in `inject_elements'
lib/misty/http/method_builder.rb:35:in `method_call'
lib/misty/http/method_builder.rb:6:in `method_missing'
```
I suspect that the cause is to be found in the generated Api hash. I've found that the format in manila Api hashmap is different from others services, ss can be seen here, for example:
`"/ v2 / {tenant_id} / os-share-manage" => {: POST => [: manage_share],: version => {: min => "2.0",: max => "2.6"}}`

I think the key **:version** makes the parsing impossible.

Can you please take a look into that?

**Comment by gildub** [comment]
@andypf, the `:version` is likely the culprit, I'll look at it. Thanks

**Comment by gildub** [comment]
@andypf, PR https://github.com/flystack/misty/pull/102 should address it, please confirm. Thanks!

**Comment by andypf** [comment]
Thanks for the time and effort!
These are a few places where GET has been replaced by METHOD. I do not know if that's what it's meant to be.

**Comment by gildub** [comment]
@andypf, sorry for not replying earlier, between Xmas, new year shut-down and down under summer break... 
Yeah METHOD is for generic request, Openstack idiosyncrasies. Since they're handled for now the best thing would be to remove them.

**Comment by gildub** [comment]
@andypf, METHOD is gone. Thanks!

https://github.com/flystack/misty/pull/106
