### ISSUE TITLE
swift and download json files

### ISSUE THREAD

**Issue by hgw77** [flystack/misty#105]
I found a small bug related to the behavior that misty converts automatically returned json to hashes. 

The bug happenes when I use ``get_object_content_and_metadata`` to download a json file from the object storage. In that case I get a hash instead a json. I did a small [workarround](https://github.com/sapcc/elektra/blob/master/plugins/object_storage/app/services/service_layer_ng/object_storage_service.rb#L198-L203) an just revert the file back into json but I thought I will give you feedback about that problem.

**Comment by gildub** [comment]
@hgw77, sorry for not replying earlier, between Xmas, new year shut-down and down under summer break...

Thank you for the feedback. I'll look into it.

**Comment by gildub** [comment]
@hgw77, you're right `get_object_content_and_metadata` returns with content-type "application/octet-stream". It needs to not be decoded. I'm adding it using a list of mime/types that won't be decoded. 

In the meantime you should be able to use #131 to inject ":content_type => :json" for that specific request.

**Comment by gildub** [comment]
@hgw77, https://github.com/flystack/misty/pull/132 should address it, could you please confirm?

**Comment by gildub** [comment]
@Carthaca, do you mind checking with Hans?

**Comment by gildub** [comment]
This issue has been addressed please re-open if needed.
