### ISSUE TITLE
OpenLab CI Integration 

### ISSUE THREAD

**Issue by gildub** [flystack/misty#116]
The [OpenLab](https://openlabtesting.org/) project is offering amazing OpenStack public clouds environments for Continuous Integration. It  would be a fantastic opportunity for Ruby SDKs such as Misty to validate its features.

**Comment by mrhillsman** [comment]
Hi @gildub 

@liu-sheng will be helping you work through this issue. Please take time to review - https://github.com/theopenlab/cicd-howto - to get an idea of expectations when setting things up.

**Comment by liusheng** [comment]
Hi @gildub,
Yes, I am one of the maintainers of the OpenLab, please feel free to ping me if you need any help :)

**Comment by gildub** [comment]
@mrhillsman, thank you!

@liu-sheng, nice to meet you again (I think we met during Denver's PTG)

**Comment by gildub** [comment]
[TheOpenLab App]( https://github.com/apps/theopenlab-ci) has been added to [Misty repo](https://github.com/organizations/flystack/settings/installations/90898).

**Comment by liusheng** [comment]
Hi @gildub,

I have do a test for the OpenLab CI integration, I have added a job for testing and a PR to trigger the Misty job, the testing result you can see  in PR: https://github.com/liu-sheng/misty/pull/2. But I am not familar with Ruby, so I am not sure if I am on the right way. In the job definition, I just running the `rake test TESTOPTS='-v'` command after installing the dependencies of Misty, is this OK ? Seems no tests run failed, you can check the testing results in [here](http://80.158.23.49/logs/2/2/2b7451a1a2d4880bfaf1366ffa58c48c7a1a4089/check/misty-unit-integration-test/d09dbe1/job-output.txt.gz). for the integration tests, doesn't it need to be run with a real openstack environment ?

Thanks!

**Comment by gildub** [comment]
@liu-sheng, 

That worked like a charm, well done! Please push https://github.com/liu-sheng/misty/pull/2 or I can do it if you prefer. I will also break the unit and integration into 2 separate jobs.

For the integration, yes the next step would be to replace the VCR cassettes mocking Openstack HTTP sessions with proper tests against DevStack. @mrhillsman kindly explained to me the details of adding Ansible playbooks folders so we can make that happen very soon.

**Comment by liusheng** [comment]
@gildub,

Ok, I have submit a [PR ](https://github.com/theopenlab/openlab-zuul-jobs/pull/67) to the OpenLab `openlab-zuul-jobs` repo to for adding two jobs of unit and integration. Will also add PR for adding the `.zuul.yaml` file to misty repo, which it the job entrypoint.

Thanks!

**Comment by gildub** [comment]
@liu-sheng, thanks.

**Comment by mrhillsman** [comment]
Hey @liu-sheng thanks for your hard work on this. What we want to do is move the jobs out of openlab-zuul-jobs and have them maintained in-repo so that developers of Misty do not have to issue PRs against an additional project/repo; they can continue to work on one codebase.

@gildub based on our last discussion are you able to pull the jobs into the misty repo

**Comment by gildub** [comment]
@mrhillsman, absolutely, please confirm with https://github.com/flystack/misty/pull/123

@liu-sheng, how do we specify ruby versions to test? Like in Travis, although the list is too long ATM and to be reduced to only the head of each main release.

**Comment by gildub** [comment]
@liu-sheng, thanks for #125, that answers my questions! :+1:
