### ISSUE TITLE
question about the license

### ISSUE THREAD

**Issue by majewsky** [flystack/misty#16]
We were looking forward to using Misty in our [custom Openstack dashboard](https://github.com/sapcc/elektra) and even started [extending it to cover one of our own OpenStack-compatible services](https://github.com/sapcc/misty-limes), but I'm not sure about the legality of these endeavors after discovering that Misty is licensed under GPL v3 and is thus incompatible with our applications which must (due to corporate requirements) be licensed under Apache v2. Are you willing to change the license to LGPL v3 to allow us to safely and legally use Misty within our open-source applications?

**Comment by gildub** [comment]
@majewsky, thank you for your interest in Misty. Please let me investigate.

**Comment by gildub** [comment]
Thank you @majewsky  for bring this. 

Effectively, the nature of Misty library being an API facilitator to be reused for higher cloud level purposes, it makes sense to lessen the license.  

Therefore Misty is going to move to Apache License v2.0.

The move from GPL to Apache is also driven by the fact that several projects which could possibly use Misty, directly or indirectly, are using Apache License.

**Comment by majewsky** [comment]
Awesome, thanks for the quick response.

Just FYI, technically you would require approval from all contributors to switch the license. But in this case, it's okay: Your only contributor until now is @Carthaca, who is sitting next to me and happens to be on board with this change. :)

**Comment by Carthaca** [comment]
👍

**Comment by hgw77** [comment]
👍

**Comment by gildub** [comment]
@majewsky, hopefully you're right!
