### ISSUE TITLE
Default Openstack Region selection

### ISSUE THREAD

**Issue by aufi** [flystack/misty#2]
Thanks for great work on this project. I've seen that there is a hard-coded name for default Region. I believe that this name comes from an OpenStack installer, so it can be different on different OpenStack installations (e.g. tripleo and packstack; regionOne vs. RegionOne IIRC)

Would it be possible don't use region name in requests until user set some in options or detect it from endpoints catalog?

**Comment by gildub** [comment]
Hi @aufi , 

Thanks for the encouraging comment :)

The default is effectively "regionOne" which is used only if the user doesn't provide a `:region_id` option:
https://github.com/flystack/misty/blob/master/lib/misty/http/client.rb#L99

I don't see how avoiding the region, the catalog is based upon it.

That said as the region is defined on a per service basis it would help to have a global parameter.

**Comment by Carthaca** [comment]
A big thanks for this project from me as well!

I agree, having the option to set the region globally would help, this also makes sense for the `interface` and the `ssl_verify_mode` params imho.

**Comment by gildub** [comment]
Hi Maurice,

Thank you!

Agreed `region_id`, `interface` and `ssl_verify_mode` to be available as global options too.

**Comment by gildub** [comment]
@aufi , @Carthaca 

The region_id, interface and ssl_verify_mode are now globals.

Thanks
