### ISSUE TITLE
usage with valid user token

### ISSUE THREAD

**Issue by hgw77** [flystack/misty#22]
At the moment misty takes care of the authentication by giving the username and password in  the auth_params. But in my situation the authentication is already done and I have no password but a valid user token. Is there a way to use misty with this token and bypass the authentication in misty?

**Comment by gildub** [comment]
@hgw77, 

Yes, absolutely, the initial approach was to use a user/password for a project or domain scope authentication but other authentication means, when needed, are good to have. 

I'm looking into it.

Thanks

**Comment by hgw77** [comment]
thank you very much :-)

**Comment by gildub** [comment]
@majewsky,

To me https://github.com/flystack/misty/pull/33 is addressing a different feature.
Here we're talking about, please @hgw77 to confirm, being able to use a fully authenticated token (expressed as a valid user token).

**Comment by hgw77** [comment]
I can confirm that I can use misty with a valid user token when I use #33
