### ISSUE TITLE
some limitations when creating a gem based on misty

### ISSUE THREAD

**Issue by hgw77** [flystack/misty#26]
I started to work on a new [misty-limes gem](https://github.com/sapcc/misty-limes) based on misty to cover our own [resource management service](https://github.com/sapcc/limes) and depending on some restrictions in the misty code I have some warnings and limitations when I use my gem.

1.  ``Misty::SERVICES`` this array is freezed so I cannot expand it in my gem and need to recreate it with the downside that I only have my own service in that array.
    * is it possible to remove the freeze from Misty::SERVICES so I can use the defined services from misty too?
2. A other point is the ``Options`` variable in ``Misty::Cloud``. This is a Struct so I cannot expand ``Options`` in my gem. My only choice is here (the same as above) to recreate the ``Options`` with my own service but I loose all other services from Misty
    *  is it possible to find a other solution for ``Options`` that I can expand it without loosing all services from misty?

In any case I got warnings that ``SERVICES`` and ``Options`` are already defined and initialized.

**Comment by gildub** [comment]
@hgw77 ,

Thank you for bringing this up.

I understand the limitations and will address both of them. Although initially Struct helped, having proper objects provide more flexibility. I've already re-factored the Setup Struct, the Options and SERVICES ones were planned to be next.

**Comment by gildub** [comment]
@hgw77 ,

Following PRs should help provide more flexibility:
https://github.com/flystack/misty/pull/27
https://github.com/flystack/misty/pull/28
https://github.com/flystack/misty/pull/29

Please let me know if you're facing any issue.

**Comment by hgw77** [comment]
thank you it worked for me (all warnings are gone 👍 ) but I found a small thing that ``Misty.services`` works different than before. In the pre refactor version I got a services list like

````
alarming: aodh => ["v2"]
baremetal: ironic => ["v1"]
block_storage: cinder => ["v3", "v1"]
clustering: senlin => ["v1"]
compute: nova => ["v2.1"]
container: magnum => ["v1"]
data_processing: sahara => ["v1.1"]
data_protection: karbor => ["v1"]
database: trove => ["v1.0"]
dns: designate => ["v2"]
identity: keystone => ["v3", "v2.0"]
image: glance => ["v2", "v1"]
messaging: zaqar => ["v2"]
metering: ceilometer => ["v2"]
network: neutron => ["v2.0"]
object_storage: swift => ["v1"]
orchestration: heat => ["v1"]
search: searchlight => ["v1"]
shared_file_systems: manila => ["v2"]
````

and now I get ``Misty::services`` object. Is that a bug or a feature? ;-)

**Comment by gildub** [comment]
@hgw77 ,

Great, I'm glad the issues have been addressed.
Regarding the `Misty.services`, yes that's a bug, the feature shouldn't have changed, thanks for reporting it.
Let's keep this one open until addressed.

**Comment by gildub** [comment]
@hgw77, #40 restores the services list. Thanks!

**Comment by hgw77** [comment]
👍
