### ISSUE TITLE
Misty::Auth authenticate with ssl

### ISSUE THREAD

**Issue by Carthaca** [flystack/misty#5]
Hi,

I suggest using the same code https://github.com/flystack/misty/blob/master/lib/misty/http/client.rb#L85-L90 here: 
https://github.com/flystack/misty/blob/master/lib/misty/auth.rb#L35

I'm currently not sure about the most elegant solution, but I'm definitely not happy with simply copying the code like I did currently to get started (https://github.com/Carthaca/misty/commit/d6072b8cbdd57c5b182cb44e1530f6fd5e1ad5b2)
Maybe one of my next casual Fridays will be more casual with time for this :) 

Cheers,
Maurice

**Comment by gildub** [comment]
Hi,

That's definitely needed! Thanks

Yeah coping the code works for now but we need to have it shared. I'm thinking about having the `net_http` method in it's own module.

Cheers,
Gilles
