### ISSUE TITLE
Misty with or without Model?

### ISSUE THREAD

**Issue by gildub** [flystack/misty#58]
@seanhandley, @Carthaca 

Choose between:
* Keep Misty as a small and lightweight library that serves up JSON lib as a dependency? 
* Add a Misty::Model namespace and have a Ruby API that hides the JSON and provides syntactic sugar to the user?

**Comment by gildub** [comment]
Although I started within the same name space, I'm now a candidate of having the sugar coating Model in a separate gem.

**Comment by Carthaca** [comment]
I would like to keep it lightweight: without model

**Comment by hgw77** [comment]
I think the same way like @Carthaca keep it lightweight without model

**Comment by andypf** [comment]
I'd make it even lighter, get away from predefined services. Misty could respect the service catalog and depending on what this catalog contains, offer the corresponding services. Services are dependent on scope. This would allow, for example, very easily to add new (own) services.

I want an Openstack client, which makes only the authentication, service and version discovery and the rest is simply the direct API communication (with headers, microversion ect.).

Example:
misty.identity.show_project_details (id, filter) -> misty.identity("v3/projetcs/#{id}", filter)
OR
misty.identity. list_projects_for_user(user_id) -> misty.identity("v3/users/#{user_id}/projects")

And it could define a method named map_to(class) which maps the response body to the given class

->  misty.identity("v3/projetcs/#{id}", filter).map_to(Project)

**Comment by seanhandley** [comment]
I don't mind where it ends up living, so long as it happens!

Are you guys interested in working on the model layer? I'm happy to give it some focus on a separate gem and pull misty in as the workhorse. Should that be a part of flystack?

I'm thinking the equivalent of Shade, but in Ruby, with all the wisdom and community direction of the SDK WG behind it.

**Comment by gildub** [comment]
Well, lightweight seems to be the preferred choice, so far.

Flystack was created so Misty is owned by an open organization (and not just me) and it can be the place holder for the new model gem unless the votes go for a different name/organization?

**Comment by gildub** [comment]
@seanhandley, @Carthaca, @hgw77, @andypf,

I had [Foggy](https://github.com/flystack/foggy) on the back burner for months, I just added the missing bits so we have an initial framework to get started quickly (no `#save`, `#create` yet). 

For a given Service (i.e Networking), each Collection (Plural name) such as Networks, Subnets, Routers, etc, is dealing with a set of Element (Single name).. 
The Collection has methods such as `all`, `get(id)`, `reload`, `save` while each Element allow to manage it, with setter/getter method.
Besides, the [plural and single names](https://github.com/flystack/foggy/blob/master/lib/foggy/service/networking.rb) there is no code, although if needed that can be added to handle special cases.

Well maybe easier to look at it or play with it, Foggy gem 0.1.0 is available.

Let me know what you think and let's meet on Foggy to eventually continue the journey :)

**Comment by seanhandley** [comment]
Sounds good @gildub - I'll be giving this some of my upstream dev time over the next few months 👍

**Comment by seanhandley** [comment]
I've started work on this over at https://github.com/datacentred/hazy - happy to transfer to flystack so it's all flying under the same banner.
