### ISSUE TITLE
allow all Keystone V3 auth param combinations

### ISSUE THREAD

**Issue by Carthaca** [flystack/misty#7]
Hi,

currently only user-name, domain-id and project-name are supported.
Would be nice to have the full combination set of user-name/-id & domain-name/-id & project-name/-id.

As before, when time allows I will send a PR ;)

Cheers,
Maurice

**Comment by gildub** [comment]
Hi Maurice,

👍 , Yes that would definitely offer more flexibility! 

I'll see if I can do that in the next few days or take yours if not.

Thanks, 
Gilles

**Comment by Carthaca** [comment]
Thanks!

**Comment by gildub** [comment]
@Carthaca, you're welcomed!
