### ISSUE TITLE
how to handle bulk-delete for swift?

### ISSUE THREAD

**Issue by hgw77** [flystack/misty#89]
I tried to use ``bulk-delete`` in swift but at the moment it seems it is not possible to use this with misty?

The normal delete needs the container and/or path to the object to delete but with [bulk-delete](https://www.swiftstack.com/docs/admin/middleware/bulk.html#bulk-delete) a path is not necessary. Instead of that we need to send DELETE with the list of objects and containers in the body and a ``?bulk-delete=1`` in the query. 

I checked the [code ](https://github.com/flystack/misty/blob/master/lib/misty/http/method_builder.rb#L29 ) and to send in misty data with ``DELETE`` is not possible. Than I checked the [swift module](https://github.com/flystack/misty/blob/master/lib/misty/openstack/swift/swift_v1.rb#L18) and there is no possiblity to send the ``DELETE`` with ``bulk-delete`` query and the object list in the body

Any idea how to add ``bulk-delete`` support to ``Misty::Openstack::SwiftV1``

**Comment by gildub** [comment]
@hgw77, according to [1], a `bulk-delete` must be submitted using POST along passing the containers/objects list via the data, and passing `Content-Type` with `text/plain`. The later can be done, as you know, using custom headers [2] .

That said, no worries for adding a method to extend Misty::Openstack::SwiftV1 wrapping the above.

[1] https://docs.openstack.org/swift/latest/middleware.html#bulk-delete
[2] https://github.com/flystack/misty/pull/88

**Comment by hgw77** [comment]
ok thank, I will add a new method to Misty::Openstack::SwiftV1 :-)

**Comment by hgw77** [comment]
added bulk_delete #90 with the custom headers it works very nice 👍

**Comment by gildub** [comment]
#92 is the wrapper feature I was talking about and as I said, although #90 is very nice it can't be done on those Openstack files directly because the "API Schema" is going to be externalized.

**Comment by gildub** [comment]
#92 is now effective with help of #93
